### ISSUE TITLE
Healing Stream Totem II - ID

### ISSUE THREAD

**Issue by TheSpanishInq** [SwimmingTiger/LibTotemInfo#1]
GetTotemInfo.lua line 80:
        spellids = { 5394, 6375, 6377, 10462, 10463, },

**Comment by SwimmingTiger** [comment]
OK, will add this.

**Comment by achillowy** [comment]
Searing Totem is not work.

**Comment by SwimmingTiger** [comment]
A high-level shaman character is required for testing. I am seeking testing assistance.

**Comment by SwimmingTiger** [comment]
I have released [v1.0.2](https://github.com/SwimmingTiger/LibTotemInfo/releases) and it should fix the problem.

The `TotemSpells` database is generated from within the game with the following code, so there should be no more missing.
https://github.com/SwimmingTiger/LibTotemInfo/wiki/Generate-the-TotemSpells-table

**Comment by Alkaersig** [comment]
I still only get timers on Rank 1 totems using TotemTimers Classic. Dont know if it is related to this.

**Comment by SwimmingTiger** [comment]
@Alkaersig Please try [v1.0.4](https://github.com/SwimmingTiger/LibTotemInfo/releases). I made a mistake in v1.0.2 that I added Totem's Rank to the spell name returned by the GetTotemInfo API with a wrong way, which caused the problem.

Some addons (like TotemTimer) use spell names for matching. Attaching rank to the spell name will cause the match to fail.

In v1.0.4, the lib add rank to spell name likes Blizzard's old interface (`xxx Totem I`, `xxx Totem II`, ...). This should fix the previous problem.

**Comment by SwimmingTiger** [comment]
The addon retired due to the return of totem functions in Wow classic 1.13.4.
