### ISSUE TITLE
[From CurseForge] High-Rank totem timer is incorrect

### ISSUE THREAD

**Issue by SwimmingTiger** [SwimmingTiger/LibTotemInfo#4]
Last edited by Zanadian: 14 mins ago

> Hi and thanks for taking the time to develop this totem mod replacement api.
>
> Some background on issue with Searing totem and any Water totem dropped I'm experiencing.
>
> I use Weakauras along with your totem mod api and have found the following happening when dropping Searing totem and any Water Totems. First i drop Searing Totem Rank 4 which is only 45 seconds length totem. The totem drops and shows a 60 second timer length which is too long at rank 4. I believe Rank 6 it is 55 seconds which you have in your lua file. I then drop Mana spring or Healing stream totem and the weakauras icon totem for the Searing totems disappears but the actual totem is still present this happens with any rank Searing totem. If i put down another Searing totem it causes any of the Water totems weakauras icon totem to disappear but the actual water totem is there not the weakauras icon. Water Totems tested are Healing stream Ranks 1,2,3 Mana Spring Rank 1,2, Tremor , Poision Cleansing, 
>
> I haven't noted any other issues.
>
> I appreciate all your time in making this mod.

**Comment by SwimmingTiger** [comment]
The addon currently does not handle Totems of Rank II or above correctly. I need a high-level Shaman character to test to get the relevant data. I am seeking testing assistance.

**Comment by corporategoth** [comment]
@SwimmingTiger FYI, in my mod I corrected for this (ie. the variable length timer based on rank), feel free to steal the code.  Also fixed Healing Stream #2, I had the wrong ID for that spell.

**Comment by corporategoth** [comment]
FYI, I am keeping my source controlled version of the mod here: https://git.neuromancy.net/projects/RM/repos/rotationmaster/browse/Libs/!TotemModFix/TotemModFix.lua

**Comment by SwimmingTiger** [comment]
I have released [v1.0.2](https://github.com/SwimmingTiger/LibTotemInfo/releases) and it should fix the problem.

`TotemSpells` database is generated from within the game with the following code, so there should be no more missing.
https://github.com/SwimmingTiger/LibTotemInfo/wiki/Generate-the-TotemSpells-table

**Comment by SwimmingTiger** [comment]
The addon retired due to the return of totem functions in Wow classic 1.13.4.
