### ISSUE TITLE
Shaman Totem Test Assistance Wizard

### ISSUE THREAD

**Issue by SwimmingTiger** [SwimmingTiger/LibTotemInfo#5]
1. Install [LogTotemInfo.zip](https://github.com/SwimmingTiger/LibTotemInfo/files/3975558/LogTotemInfo.zip) to your `World of Warcraft\_classic_\Interface\Addons` and enable it.
2. Cast a totem spell. You will see debugging information in the chat window.
   
   ![step2](https://user-images.githubusercontent.com/4986069/71035675-ee788000-2156-11ea-99e7-b78420173584.png)
3. Wait for the totem effect to finish, then cast the next totem spell.
   If you don't have enough time, you don't have to wait for the totem effect to end. You can cast the next one after the first totem appears.
4. Cast all totem spells you own, including all levels.
5. Quit the game normally from the game menu (don't use Alt + F4 or Task Manager, or the test result will not be saved).
6. Find this file and paste it here.
    If you don't have a GitHub account, you can send it to `hu60.cn@gmail.com`.
   
   ```
   World of Warcraft\_classic_\WTF\Account\<your-account-id>\SavedVariables\LogTotemInfo.lua
   ```
   For me, it is:
   ```
   World of Warcraft\_classic_\WTF\Account\186560409#3\SavedVariables\LogTotemInfo.lua
   ```
   ![step6](https://user-images.githubusercontent.com/4986069/71036013-c2113380-2157-11ea-8193-0f18c5bf692e.png)

Then you have completed the test assistance. Thank you very much!

**Comment by ronivay** [comment]
Hi,

I’ll deliver some debug data later today if anyone else haven’t already by then.

**Comment by tjunno** [comment]
LogTotemInfo = {
	{
		["time"] = "[08:56:06]",
		["args"] = {
			"player", -- [1]
			"Cast-3-4468-0-96-836-000179E9A4", -- [2]
			836, -- [3]
		},
		["spellInfo"] = {
			"LOGINEFFECT", -- [1]
			nil, -- [2]
			136235, -- [3]
			0, -- [4]
			0, -- [5]
			0, -- [6]
			836, -- [7]
		},
		["event"] = "UNIT_SPELLCAST_SUCCEEDED",
		["spellID"] = 836,
	}, -- [1]
	{
		["time"] = "[08:57:14]",
		["args"] = {
			"player", -- [1]
			"Cast-3-4468-0-96-6377-000079E9EB", -- [2]
			6377, -- [3]
		},
		["spellInfo"] = {
			"Healing Stream Totem", -- [1]
			nil, -- [2]
			135127, -- [3]
			0, -- [4]
			0, -- [5]
			0, -- [6]
			6377, -- [7]
		},
		["event"] = "UNIT_SPELLCAST_SUCCEEDED",
		["spellID"] = 6377,
	}, -- [2]
	{
		["time"] = "[08:57:15]",
		["args"] = {
			3, -- [1]
		},
		["event"] = "PLAYER_TOTEM_UPDATE",
		["spellID"] = 6377,
	}, -- [3]
	{
		["time"] = "[08:58:16]",
		["args"] = {
			3, -- [1]
		},
		["event"] = "PLAYER_TOTEM_UPDATE",
		["spellID"] = 6377,
	}, -- [4]
}

**Comment by ronivay** [comment]
Hi,

I just sent you an email containing log file from a lvl60 shaman with all possible totems and ranks. Hope this helps!

**Comment by SwimmingTiger** [comment]
Thank you. Your data is helpful. I am working on the problem fix.
